### ISSUE TITLE
Wool on Ender Chest doesn't get removed sometimes

### ISSUE THREAD

**Issue by EnderBro123** [TheBusyBiscuit/ColoredEnderChests#3]
This usually happens to the right wool.

![2019-06-19_09 49 37](https://user-images.githubusercontent.com/51277766/59784550-903a1580-9277-11e9-98a7-a1627b46cff9.png)

![2019-06-19_09 49 59](https://user-images.githubusercontent.com/51277766/59784573-9fb95e80-9277-11e9-9ea4-1cc3b72e9f64.png)

**Comment by robbcrg** [comment]
Did anyone find a solution for this? I just had it happen to me and I cannot remove that little bit of wool no matter what. I think it happened as I broke the chest and had a lag spike (caused by other activity).

It's not a big deal except cosmetically as it only happened once. But if anyone has a suggestion how to fix this I would really appreciate it.

![image](https://user-images.githubusercontent.com/11152254/118024998-a10a3d80-b35f-11eb-9eb7-63259b89ce1a.png)

Slimefun4 - DEV 899 (git c29d0).jar
ColoredEnderChests - DEV 22 (git 7c926).jar
This server is running Paper version git-Paper-643 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by MagmaBro123** [comment]
> Did anyone find a solution for this? I just had it happen to me and I cannot remove that little bit of wool no matter what. I think it happened as I broke the chest and had a lag spike (caused by other activity).
> 
> It's not a big deal except cosmetically as it only happened once. But if anyone has a suggestion how to fix this I would really appreciate it.
> 
> ![image](https://user-images.githubusercontent.com/11152254/118024998-a10a3d80-b35f-11eb-9eb7-63259b89ce1a.png)
> 
> Slimefun4 - DEV 899 (git c29d0).jar
> ColoredEnderChests - DEV 22 (git 7c926).jar
> This server is running Paper version git-Paper-643 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

/kill @e[type=!player,distance=..5]

@TheBusyBiscuit I gave you the needed info.
